---
abstract: 'bringing JSON functions to autobox'
author:
  - 'Robin Edwards <robin.ge@gmail.com>'
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autobox-JSON
requires:
  JSON: 2.50
  autobox: 2.72
version: 0.0002
